### ISSUE TITLE
Procfile definitions for systemd.resource-control settings

### ISSUE THREAD

**Issue by gongled** [funbox/init-exporter#42]
Hello everyone,

I suppose that would be nice to implement [systems.resource-control](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html) options to limit applications by CPU, RAM, I/O etc. from the `Procfile` definition. 

On the one hand, it might be useful for those people, who run multiple applications on one server and want to assign particular amount of systems resources. On the other hand, it works only with `systemd` whereas `upstart` supervisor does not have this feature out-of-box.

What do you think? Let's discuss this further.

**Comment by vassilevsky** [comment]
So far I see only one useful aspect of it: protect the server from application bugs.

System limits could be set to ~90% of maximum values a server can handle. It could be done even globally in the templates, without any per-app settings. They will keep application bugs from rendering servers unusable.

But there must be notifications when these limits are reached. Otherwise it's pointless.

I don't see a reason why an application maintainer would want to add limits to app configs. Nobody likes to limit themselves 🙃 And all programmers are always sure that their apps have no bugs and don't leak resources.

**Comment by andyone** [comment]
@gongled Good idea. Added in 9bc6001066db41b55cf375c0e30738a62d0546d9 and will be released as part as 0.20.0 release.

**Comment by andyone** [comment]
Version `0.20.0` has been released.
