### ISSUE TITLE
Systemd: reload_signal does not work on CentOS 7

### ISSUE THREAD

**Issue by gongled** [funbox/init-exporter#57]
### Bug report

**System info:**

* **Version used:** 0.21.0
* **OS (`cat /etc/*-release`):** CentOS 7
* **Kernel (`uname -a`):** `3.10.0`

**System info:**

1. Create `Procfile` with the `reload_signal` option defined.
2. Export given procfile to systemd.
3. Start systemd unit.
4. Run `reload` command using `systemctl`.

**Expected behavior:**

Command `reload` sends defined signal to the process.

**Actual behavior:**

`systemd` sends signal to parent process, whose helper does not handle signal and does not forward to its child process. So child process is unable to trap and process the signal.

**Additional info:**

Possible solutions:
1. Declare `trap` inside init-exporter helpers with given signal and `sigHandler` which sends signal to child process.
2. Provide mechanism to use custom `ExecReload` command (not only `kill`).

**Comment by andyone** [comment]
Hi! Thanks for your report and investigation.

> Declare trap inside init-exporter helpers with given signal and sigHandler which sends signal to child process.

Signals can't be handled by the helper without sending service command to the background. In this case, we will have to remove `exec` which helps us with access restrictions ([more info](https://www.computerhope.com/unix/bash/exec.htm#description)).

> Provide mechanism to use custom ExecReload command (not only kill).

It is impossible due to security reasons. User must not be able to provide any command which will be executed under `root` user.

I think we should remove `reload_signal` support for both init systems.

**Comment by andyone** [comment]
`reload_signal` support removed in f147eec

**Comment by lunahike** [comment]
You can try using the command `pkill` instead `kill`. It works for me.
```
ExecReload=/bin/pkill -SIGUSR2 -P $MAINPID
```

**Comment by andyone** [comment]
Reload signal feature was reimplemented in 0903f5a9d38ae52d603fd8bb649e7cc84f610a3b
